name: playground-actions
on: [ push ]
jobs:
  restore:
    name: Restore packages
    runs-on: ubuntu-latest
    steps:
      - run: dotnet restore
  build:
    name: Building application
    runs-on: ubuntu-latest
    steps:
      - run: dotnet build --no-restore
  test:
    name: Test application
    runs-on: ubuntu-latest
    steps:
      - run: dotnet test --no-build --verbosity normal
  deploy:
    name: Build docker file
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build docker file processed successfully"